Fixing duplicate dbset from dbcontext, changing table title name, fixing function from BillInfoesController
mickarena/FresherMVC pull request #28
Opened 2022-10-06 03:02 UTC by Shiro-2002

2022-10-06 09:36 UTC, mickarena commented
rejected

2022-10-07 08:22 UTC, vuanh1906 requested changes

2022-10-07 08:22 UTC, vuanh1906 commented on Skinet/Infrastructure/Data/MedBillInfoRepository.cs
> +            return _context.MedicineBillInfos.AsNoTracking().FirstOrDefault(c => c.Id == id);
FirstOrDefaultAsync

2022-10-07 08:22 UTC, vuanh1906 commented on Skinet/Infrastructure/Data/MedBillInfoRepository.cs
> +            return _context.MedicineBillInfos.AsNoTracking().FirstOrDefault(c => c.Id == id);
AsNoTracking() ????

2022-10-07 08:22 UTC, vuanh1906 commented on Skinet/Infrastructure/Data/MedBillInfoRepository.cs
> +            return _context.MedicineBillInfos.Include(m => m.MedicineBills).Include(c => c.MedicineInfomations).AsNoTracking().ToList();
AsNoTracking() ???

2022-10-07 08:22 UTC, vuanh1906 commented on Skinet/Infrastructure/Data/MedBillRepository.cs
> +            var temp = _context!.MedicineBills.AsNoTracking().FirstOrDefault(c => c.Id == id);
AsNoTracking() ????

2022-10-07 08:22 UTC, vuanh1906 commented on Skinet/Infrastructure/Data/MedBillRepository.cs
> +            return _context.MedicineBills.AsNoTracking().ToList();
AsNoTracking() ?????

2022-10-07 08:22 UTC, vuanh1906 commented on Skinet/Infrastructure/Data/MedInfoRepository.cs
> +            return _context.MedicineInfomations.Include(m => m.MedicineTypes).AsNoTracking().ToList();
AsNoTracking() ???

2022-10-07 08:22 UTC, vuanh1906 commented on Skinet/Infrastructure/Data/MedTypeRepository.cs
> +            return _context.MedicineTypes.AsNoTracking().ToList();
AsNoTracking() ???

2022-10-07 08:22 UTC, vuanh1906 commented on Skinet/Web/Controllers/MedicineInfomationsController.cs
> +            return _medicineInfo.GetById(id).IsCompletedSuccessfully;
thừa

2022-10-07 08:22 UTC, vuanh1906 commented on Skinet/Web/Controllers/MedicineTypesController.cs
>                  {
throw ?

2022-10-07 08:22 UTC, vuanh1906 commented on Skinet/Web/Views/MedicineBillInfoes/Create.cshtml
> +                <select asp-for="IdMedicineInfo" asp-items="ViewBag.IdMedicineInfo" class="form-control"></select>
thêm validate

2022-10-07 08:22 UTC, vuanh1906 commented on Skinet/Web/Views/MedicineBillInfoes/Create.cshtml
> +                <label class="control-label">Medince name</label>
dùng annotaion displayName trong model

2022-10-07 08:22 UTC, vuanh1906 commented on Skinet/Web/Views/MedicineBillInfoes/Delete.cshtml
> -            @Html.DisplayNameFor(model => model.IdMedicineInfo)
để lại display name for

2022-10-07 08:22 UTC, vuanh1906 commented on Skinet/Web/Views/MedicineBillInfoes/Delete.cshtml
> +            Quantity
để lại display name for

2022-10-07 08:22 UTC, vuanh1906 commented on Skinet/Web/Views/MedicineBillInfoes/Delete.cshtml
> +            Unit price
để lại display name for

2022-10-07 08:22 UTC, vuanh1906 commented on Skinet/Web/Views/MedicineBillInfoes/Delete.cshtml
> +            Total price
để lại display name for

2022-10-07 08:22 UTC, vuanh1906 commented on Skinet/Web/Views/MedicineBillInfoes/Delete.cshtml
> +            Bill Id
để lại display name for

2022-10-07 08:22 UTC, vuanh1906 commented on Skinet/Web/Views/MedicineBillInfoes/Details.cshtml
> +            Medince name
để lại display name for

2022-10-07 08:22 UTC, vuanh1906 commented on Skinet/Web/Views/MedicineBillInfoes/Details.cshtml
> +          Quantity
để lại display name for

2022-10-10 06:56 UTC, closed without merging